version: "3"
services:
  db:
    image: "postgres:10"
    container_name: "postgres_dev"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - /home/lpolon/postgres/data:/var/lib/postgresql/data:Z
    restart: always
    networks:
      - postgres
  pgadmin:
    image: "docker.io/dpage/pgadmin4:4"
    container_name: "pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
     - "80:80"
    restart: always
    networks:
      - postgres
    volumes:
      - /home/lpolon/postgres/pgadmin4:/root/.pgadmin

networks:
  postgres:
    driver: bridge
